name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  CheckClangFormat:
    name: Check clang-format
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            llvm-19
      - name: Clone tree
        uses: actions/checkout@v4
      - name: Run clang-format
        run: |
          find src \
              -iname "*.h" -o -iname "*.c" -o -iname "*.cpp" \
              -exec clang-format -n -Werror {} \+;

  BuildLibrary:
    name: Verify project may be built
    runs-on: ubuntu-latest
    env:
      NXDK_DIR: /opt/local/nxdk
    steps:
      - name: Clone tree
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            llvm \
            lld \
            ninja-build

      - name: Clone nxdk Repo
        shell: bash
        run: git clone --recursive --depth 1 https://github.com/XboxDev/nxdk.git "$NXDK_DIR"

      - name: Build nxdk
        shell: bash
        run: |
          PATH="${NXDK_DIR}/bin:$PATH" make -j $(nproc) -C "$NXDK_DIR" NXDK_ONLY=1 CFLAGS=-O2 CXXFLAGS=-O2 all

      - name: Compile
        run: |
          cmake -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_TOOLCHAIN_FILE="${NXDK_DIR}/share/toolchain-nxdk.cmake"
          cmake --build build -- -j$(grep -c processor /proc/cpuinfo)
